name: Test package

on:
  pull_request:

jobs:
  test-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Run npm setup command
        run: npm install
      - name: Test package
        uses: zakodium/test-package-action@dev
